### ISSUE TITLE
Incorrect certificate of https://exaile.org

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile.github.io#1]
As noted in exaile/exaile#631, https://exaile.org/ has an incorrect certificate, namely one for `[*.]github.com` and `[*.]github.io`.

Steps to reproduce:
1. Open https://exaile.org in your browser.

What happens:
Certificate warning ([SSL_ERROR_BAD_CERT_DOMAIN](https://support.mozilla.org/en-US/kb/what-does-your-connection-is-not-secure-mean#w_ssl-error-bad-cert-domain))

What should happen:
No warning, just as it works fine with https://www.exaile.org/

```
$ dig exaile.org
[…]
exaile.org.		86033	IN	A	192.30.252.153
exaile.org.		86033	IN	A	192.30.252.154
```

```
$ dig www.exaile.org
[…]
www.exaile.org.		86355	IN	CNAME	exaile.github.io.
exaile.github.io.	3555	IN	A	185.199.108.153
exaile.github.io.	3555	IN	A	185.199.111.153
exaile.github.io.	3555	IN	A	185.199.110.153
exaile.github.io.	3555	IN	A	185.199.109.153
```

**Comment by genodeftest** [comment]
@synic : Can you please update the DNS A records of exaile.org to
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
? That should fix the issue [according to GitHub's guide](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain).
as per [@virtuald's comment](https://github.com/exaile/exaile/pull/631#issuecomment-491633171)?

**Comment by synic** [comment]
Well, I changed it. Not sure if I did it correctly, though! Guess we'll find out soon enough.

**Comment by genodeftest** [comment]
Works fine now, thanks!
